name: 'Lint (Flake8 & Pylint)'
description: Lints Python code using Flake8 & PyLint. Outputs a pylint score badge as an artifact.
inputs:
  folders-to-exclude:
    description: Folders in repo to exclude from linting (comma separated, no spaces)
    required: false
    default: 'tests'
  ignore-failures:
    description: Set to 'true' to not fail if linters detect issues, 'false' to fail if linters detect issues.
    required: false
    default: 'true'
runs:
  using: "composite"
  steps:
    - name: Validate ignore-failures
      shell: bash
      run: $GITHUB_ACTION_PATH/../common_scripts/check_membership.sh "${{ inputs.ignore-failures }}" "true false"

    - name: Lint Code (Flake 8)
      shell: bash
      run: $GITHUB_ACTION_PATH/scripts/lint_with_flake8.sh "${{ inputs.ignore-failures }}" "${{ inputs.folders-to-exclude }}"
    
    - name: Lint Code (Pylint)
      shell: bash
      run: $GITHUB_ACTION_PATH/scripts/lint_with_pylint.sh "${{ inputs.ignore-failures }}" "${{ inputs.folders-to-exclude }}"

    - name: Generate Pylint Badge
      shell: bash
      run: $GITHUB_ACTION_PATH/scripts/generate_pylint_badge.sh

    - name: Upload Pylint Score Badge
      uses: actions/upload-artifact@v4
      with:
        name: pylint-badge-${{ github.ref_name }}-${{ github.run_id}}.svg
        path: pylint-badge.svg
        if-no-files-found: ignore

  