name: Lint (Flake8 & Pylint)
description: Lints Python code using Flake8 & PyLint. Outputs a pylint score badge as an artifact.
inputs:
  folders-to-exclude:
    description: Folders in repo to exclude from linting (comma separated, no spaces)
    required: false
    default: "tests"
  ignore-failures:
    description: Set to 'true' to not fail if linters detect issues, 'false' to fail if linters detect issues.
    required: false
    default: "true"
  github_token:
    required: true
    description: GitHub token for authentication

runs:
  using: composite
  steps:
    - name: Lint Code (Flake 8)
      shell: bash
      run: |
        "$GITHUB_ACTION_PATH/scripts/lint_with_flake8.sh" \
        "${{ inputs.ignore-failures }}" "${{ inputs.folders-to-exclude }}"
    
    - name: Lint Code (Pylint)
      shell: bash
      run: |
        "$GITHUB_ACTION_PATH/scripts/lint_with_pylint.sh" \
        "${{ inputs.ignore-failures }}" "${{ inputs.folders-to-exclude }}"
    
    - name: Get short SHA
      id: short-sha
      shell: bash
      run: |
        SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
        echo "short_sha=$SHORT_SHA" >> $GITHUB_OUTPUT

    - name: Upload Pylint Score Badge
      uses: actions/upload-artifact@v4
      with:
        name: "pylint-badge-${{ steps.short-sha.outputs.short_sha }}.svg"
        path: pylint-badge.svg
        if-no-files-found: ignore

    - name: Push Pylint Badge to Badges Branch
      shell: bash
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${{ inputs.github_token }}@github.com/${{ github.repository }}
        git checkout pylint_badges || git checkout --orphan pylint_badges
        cp pylint.json /tmp/pylint.json
        git rm -rf .
        cp /tmp/pylint.json .
        git add pylint.json
        git commit -m "Update Pylint badge from ${GITHUB_REF#refs/heads/} commit ${GITHUB_SHA}"
        git push -f origin pylint_badges 
        git checkout $GITHUB_REF_NAME

        
