name: 'Security Scan (Bandit)'
description: Performs a Bandit Security Scan on Python Code. Outputs a Scan Report (HTML) as an artifact.
inputs:
  language:
    description: Language to perform CodeQL scanning for (python, javascript) etc.
    required: true
runs:
  using: "composite"
  steps:
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ inputs.language }}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3