# This workflow is intended for Python projects managed using uv & pyproject.toml.
# This workflow installs Python dependencies, runs tests,
# lints, and performs a limited security scan using Bandit.

name: CI (UV Managed Projects)

on:
  workflow_dispatch:

jobs:
  Setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Detect Python Version
        id: detect-python
        run: |
          PYTHON_VER=""

          # Parse Python version from .python-version
          if [ -f .python-version ]; then
            PYTHON_VER=$(cat .python-version)

          # Parse Python version from pyproject.toml - picks the minimum compatible version
          elif [ -f pyproject.toml ]; then
            PYTHON_VER=$(grep 'requires-python' pyproject.toml | head -1 | cut -d'"' -f2 | sed 's/>=//')

          # Raise error if no version found
          elif [ -z "$PYTHON_VER" ]; then 
            echo "Error: No Python version detected in .python-version or pyproject.toml"
            exit 1
          fi

          echo "Detected Python version: $PYTHON_VER"
          echo "PYTHON_VER=$PYTHON_VER" >> $GITHUB_ENV

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VER }}

      - name: Install UV
        run: curl -LS https://astral.sh/uv/install.sh | sh

      - name: Cache environment
        #Caches environment so that dependencies only installed if changed between runs
        uses: actions/cache@v3
        with:
          path: .venv
          key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}

      - name: Install Dependencies 
        run: |
          uv venv
          source .venv/bin/activate

          # Parse dependencies from uv.lock
          if [ -f "uv.lock" ]; then
            echo "Installing from uv.lock"
            uv sync

          # Parse dependencies from requirements.txt  
          elif [ -f "requirements.txt" ]; then
            cat <<EOF
          No uv.lock file detected. Installing dependencies from requirements.txt.
          Recommend creating a uv.lock file. Cache is tied to uv.lock file.
          EOF 
            uv pip sync requirements.txt
          
          # Parse dependencies from pyproject.toml
          elif [ -f "pyproject.toml" ]; then
            cat <<EOF
          No uv.lock file or requirements.txt detected. Installing dependencies from pyproject.toml.
          Recommend creating a uv.lock file to lock exact versions of dependencies.
          Cache is tied to uv.lock file. 
          EOF
            uv pip install -r pyproject.toml

          else
            echo "Error: No dependency file found - expect one of uv.lock, requirements.txt or pyproject.toml"
            exit 1
          fi

      - name: Install CI Dependencies
        run: |
          # Install dependencies for CI
          CI_PACKAGES="bandit flake8 pylint pytest pytest-cov"
          source .venv/bin/activate
          uv pip install $CI_PACKAGES


  Test:
    needs: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore environment
        uses: actions/cache@v3
        with:
          path: .venv
          key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}

      - name: Run Tests
        uses: ./.github/actions/test



  Security-Scan:
    needs: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore environment
        uses: actions/cache@v3
        with:
          path: .venv
          key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}

      - name: Run Bandit Scan
        uses: ./.github/actions/scan
        with:
          exclude-folders: './tests'


  Lint:
    needs: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore environment
        uses: actions/cache@v3
        with:
          path: .venv
          key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
      
      - name: Lint
        uses: ./.github/actions/lint
        with:
          folders-to-exclude: 'tests,.venv'
          ignore-failures: 'true'

       
  Docker_Build:
    needs: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [backend, frontend]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Generate Docker Tag
        id: set_tag
        run: |
          # Get branch name and sanitise it
          BRANCH=$(echo "${{ github.ref_name || 'manual' }}" | sed 's/\//-/g')

          # Get current date
          DATE=$(date +'%Y-%m-%d')

          # Get short commit hash (fallback to workflow run ID for manual triggers)
          if [ "${{ github.sha }}" == "" ]; then
            SHORT_SHA="${{ github.run_id }}"
          else
            SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          fi

          # Combine them into the Docker tag
          TAG="${BRANCH}-${DATE}-${SHORT_SHA}"
          echo "Generated Tag: $TAG"
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Build and tag Docker image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --tag cicdtemplate/${{ matrix.service }}:${{ env.TAG }} \
            --file ./src/${{ matrix.service }}/Dockerfile \
            ./src/${{ matrix.service }} \
            --load
          docker save cicdtemplate/${{ matrix.service }}:${{ env.TAG }} -o ${{ matrix.service }}-${{ env.TAG }}.tar

      - name: Upload Image
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.service }}-${{ env.TAG }}
          path: ${{ matrix.service }}-${{ env.TAG }}.tar
          if-no-files-found: ignore



          



