# This workflow is intended for Python projects
# This workflow installs Python dependencies, runs tests,
# lints, security scans and build Docker images.

name: CI Template Process

on:
  workflow_dispatch:

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Detect Python Version
        id: python
        uses: ./.github/actions/detect_python
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ steps.python.outputs.version }}

      - name: Install Dependencies
        uses: ./.github/actions/install_dependencies
        with:
          dependency-manager: 'uv' 
        

  Test:
    needs: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore environment
        uses: ./.github/actions/restore_env_from_cache
        with:
          dependency-manager: 'uv'

      - name: Run Tests
        uses: ./.github/actions/test


  Security-Scan:
    needs: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore environment
        uses: ./.github/actions/restore_env_from_cache
        with:
          dependency-manager: 'uv'

      - name: Run Bandit Scan
        uses: ./.github/actions/scan
        with:
          exclude-folders: './tests'


  Lint:
    needs: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore environment
        uses: ./.github/actions/restore_env_from_cache
        with:
          dependency-manager: 'uv'
      
      - name: Lint
        uses: ./.github/actions/lint
        with:
          folders-to-exclude: 'tests,.venv'
          ignore-failures: 'true'

       
  Docker_Build:
    needs: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        context: [./src/backend, ./src/frontend]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Image
        uses: ./.github/actions/build
        with:
          build-context: ${{ matrix.context }}
          cloud-registry: "none"
          build-platform: "linux/amd64"

      


